apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "envoy-proxy.fullname" . }}
  labels:
    {{- include "envoy-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "envoy-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "envoy-proxy.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 10000
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
